[project]
authors = ["Betim H <106614572+Betim-Hodza@users.noreply.github.com>"]
channels = ["https://conda.modular.com/max", "https://conda.modular.com/max-nightly", "https://repo.prefix.dev/modular-community", "conda-forge"]
description = "Add a short description here"
name = "DFA_1"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
max = ">=24.6.0,<25"
